

export const procedureImages = [
  { name: "Zmiana worka stomijnego na kolostomii", image: require('../assets/images/procedures/stoma-bag.png'), },
  { name: "Pielęgnacja gastrostomii po ponad 14 dniach od założenia", image: "" },
  { name: "Podskórne podanie insuliny wstrzykiwaczem typu pen", image: "" },
  { name: "Zasady podawania leków", image: "" },
  { name: "Nebulizacja w domu pacjenta", image: "" },
  { name: "Zmiana worka stomijnego na ileostomii", image: "" },
  { name: "Pomiar ciśnienia", image: "" },
  { name: "Przygotowanie i pobranie moczu", image: "" },
  { name: "Zmiana opatrunku na ranie powikłanej", image: "" },
  { name: "Pomiar oddechu", image: "" },
  { name: "Okład wysychający", image: "" },
  { name: "Zmiana opatrunku wokół tracheostomii w pierwszych 14 dniach od zabiegu", image: "" },
  { name: "Technika mycia i dezynfekcji rąk według schematu AYLIFFE'A", image: "" },
  { name: "Opieka nad pacjentem z zaburzeniami połykania (zasady bezpiecznego karmienia osób z zaburzeniami połykania)", image: "" },
  { name: "Podanie leków doodbytniczo", image: "" },
  { name: "Zasady tlenoterapii", image: "" },
  { name: "Odłączanie kroplowego wlewu dożylnego", image: "" },
  { name: "Zasady pielęgnacji gastrostomii przez pierwsze 14 dni od założenia", image: "" },
  { name: "Ogólne zasady transportu pacjenta za pomocą podnośnika", image: "" },
  { name: "Okład rozgrzewający", image: "" },
  { name: "Dobowa zbiórka moczu", image: "" },
  { name: "Pomiar glikemii", image: "" },
  { name: "Karmienie przez zgłębnik nosowo-żołądkowy", image: "" },
  { name: "Podanie heparyny drobnocząsteczkowej", image: "" },
  { name: "Płukanie ran", image: "" },
  { name: "Instrukcja pobrania kału", image: "" },
  { name: "Zmiana opatrunku na ranie niepowikłanej", image: "" },
  { name: "Podanie leku na skórę", image: "" },
  { name: "Mierzenie tętna", image: "" },
  { name: "Odsysanie drzewa oskrzelowego", image: "" },
  { name: "Pobieranie krwi żylnej", image: "" },
]; 